//! Code-owned guard classifications only. Never attach provider values or parser errors.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ResponseStage {
    Headers,
    HeaderFraming,
    ContentType,
    Redirect,
    BodyBounds,
    RoutingState,
    BodyFraming,
    SseFraming,
    Json,
    EventBounds,
    EventEnvelope,
    EventKind,
    SequenceField,
    Sequence,
    Lifecycle,
    ResponseIdentity,
    ResponseModel,
    TextDelta,
    RefusalDelta,
    ArgumentDelta,
    CompletedEnvelope,
    CompletedIdentity,
    Usage,
    AssistantMessage,
    Reasoning,
    FunctionCall,
    OutputConsistency,
    Termination,
}
