[package]
name = "morons-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "morons-server"
path = "src/main.rs"

[dependencies]
interprocess.workspace = true
morons-protocol = { path = "../morons-protocol" }
tokio = { workspace = true, features = ["io-util", "macros", "rt", "signal", "time"] }
