[package]
name = "morons-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "morons-server"
path = "src/main.rs"

[dependencies]
getrandom.workspace = true
interprocess.workspace = true
morons-protocol = { path = "../morons-protocol" }
rusqlite.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "rt", "signal", "sync", "time"] }
zeroize.workspace = true

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["process", "std"] }

[target.'cfg(windows)'.dependencies]
fence-windows.workspace = true

[dev-dependencies]
morons-cli = { path = "../morons-cli" }
